CREATE TABLE currency (
    ticker varchar(10) CONSTRAINT ticker_pk PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE currency_pair (
    id int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT currency_pair_pkey PRIMARY KEY,
    base_ticker varchar(10) NOT NULL ,
    quoted_ticker varchar(10) NOT NULL,
    is_available boolean NOT NULL,
    CONSTRAINT base_quoted_unique UNIQUE (base_ticker, quoted_ticker),
    CONSTRAINT base_ticker_fkey FOREIGN KEY (base_ticker) REFERENCES currency(ticker),
    CONSTRAINT quoted_ticker_fkey FOREIGN KEY (quoted_ticker) REFERENCES currency(ticker)
);

INSERT INTO currency (ticker, name)
VALUES ('BTC', 'Bitcoin'),
       ('USDT', 'Tether'),
       ('ETH', 'Ethereum'),
       ('BCH', 'Bitcoin Cash'),
       ('XRP', 'XRP'),
       ('LTC', 'Litecoin'),
       ('BNB', 'Binance Coin');

INSERT INTO currency_pair (base_ticker, quoted_ticker, is_available)
VALUES ('BTC', 'USDT', true),
       ('ETH', 'BTC', true),
       ('BCH', 'BTC', true),
       ('XRP', 'BTC', true),
       ('LTC', 'BTC', true),
       ('BNB', 'ETH', true);